### ISSUE TITLE
Sample ordering

### ISSUE THREAD

**Issue by lucmans** [Signalsmith-Audio/signalsmith-stretch#2]
Normally, when working with (a stream of) samples, the channels are interleaved (L1R1L2R2...LnRn).
Your library expects all the samples of one channel to be contiguous (L1L2...LnR1R2...Rn).

In my experience, audio is mostly handled in the interleaved format, forcing devs using this lib to adapt their buffers (or access to its content).
I would suggest adding an interleaved interface to your lib.

**Comment by mdabbs** [comment]
You could write a class that overloads the [] operator and then take the provided index to that method, double it, then use your channel index.  I've thought about doing this, but since my samples are signed 16-bit ints, I chose not to go this way because the lib accesses the inputs and outputs multiple times which means I would be scaling them back and forth multiple times.  I chose the buffer filling technique instead because memory is cheaper than mults/divs and I already have to fill a buffer anyway, might as well fill it with only scaling once.

**Comment by geraintluff** [comment]
It's interesting that you've mostly encountered interleaved audio!  I've not personally encountered it outside of WAV files, and separate buffers are a much more common situation for audio plugins.

Copying to a buffer seems fairly sensible to me, particularly if there's int/float conversion going on as well.  I'm closing this issue, but if someone else asks about the same thing, then I'll consider including a utility class for interleaved access.
